# Generated by Django 3.0.5 on 2020-05-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fintech_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfidatabase',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
