# Generated by Django 3.0.5 on 2020-05-10 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fintech_website', '0002_auto_20200510_0711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMFIDatabase',
        ),
    ]
