# Generated by Django 3.0.5 on 2020-05-10 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fintech_website', '0006_amfidata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amfidata',
            name='from_date',
        ),
    ]
