# Generated by Django 3.0.5 on 2020-05-11 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fintech_website', '0008_niftydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niftydata',
            old_name='tri',
            new_name='TRI',
        ),
    ]
