# Generated by Django 3.0.5 on 2020-05-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('fintech_website', '0010_auto_20200512_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amfidata',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amfidata',
            name='name',
            field=models.TextField(),
        ),
    ]
