# Generated by Django 3.0.5 on 2020-05-23 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fintech_website', '0011_auto_20200512_0446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NIFTYdata',
        ),
    ]
