# Generated by Django 3.0.5 on 2020-05-23 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fintech_website', '0013_niftydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NIFTYdata',
        ),
    ]
