# Generated by Django 3.0.5 on 2020-05-25 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('fintech_website', '0015_niftydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NIFTYdata',
        ),
    ]
